# Generated by Django 4.2.16 on 2026-03-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIPTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do App')),
                ('notas', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('dns', models.CharField(max_length=500, verbose_name='DNS / URL')),
                ('porta', models.IntegerField(default=80, verbose_name='Porta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notas', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ListaCanais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Lista')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=200, verbose_name='Senha')),
                ('num_telas', models.PositiveSmallIntegerField(default=1, verbose_name='Qtd. de Telas')),
                ('dns_customizado', models.CharField(blank=True, help_text='Preencha apenas se for diferente do servidor', max_length=500, verbose_name='DNS Customizado')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensalidade (R$)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, verbose_name='Dia do Vencimento')),
                ('ultima_atualizacao', models.DateField(blank=True, null=True, verbose_name='Última Atualização da Lista')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notas', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='clientes.cliente', verbose_name='Cliente')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_pagas', to='clientes.pagador', verbose_name='Pagador')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas', to='listas.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Lista de Canais',
                'verbose_name_plural': 'Listas de Canais',
                'ordering': ['cliente__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ListaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_app', models.CharField(blank=True, max_length=200, verbose_name='Usuário no App')),
                ('senha_app', models.CharField(blank=True, max_length=200, verbose_name='Senha no App')),
                ('device_id', models.CharField(blank=True, max_length=200, verbose_name='Device ID / MAC')),
                ('notas', models.TextField(blank=True, verbose_name='Observações')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.appiptv', verbose_name='Aplicativo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='listas.listacanais', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'App da Lista',
                'verbose_name_plural': 'Apps da Lista',
            },
        ),
    ]
