# Generated by Django 4.2.16 on 2026-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listacanais',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='appiptv',
            name='servidores',
            field=models.ManyToManyField(blank=True, related_name='apps', to='listas.servidor', verbose_name='Servidores compatíveis'),
        ),
        migrations.AddField(
            model_name='listacanais',
            name='data_ativacao',
            field=models.DateField(blank=True, help_text='Define o dia de vencimento mensal (ex: ativado dia 10 → vence todo dia 10)', null=True, verbose_name='Data de Ativação'),
        ),
    ]
