# Generated by Django 4.2.16 on 2026-03-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_remove_listacanais_dia_vencimento_appiptv_servidores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('preco_por_tela', models.DecimalField(decimal_places=2, help_text='Valor cobrado do cliente por cada tela/acesso', max_digits=10, verbose_name='Preço por Tela (R$)')),
                ('custo_por_tela', models.DecimalField(decimal_places=2, help_text='Seu custo por cada tela/acesso', max_digits=10, verbose_name='Custo por Tela (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco_por_tela', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='listacanais',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas', to='listas.plano', verbose_name='Plano'),
        ),
    ]
