# Generated by Django 4.2.16 on 2026-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_plano_listacanais_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacanais',
            name='aparelho',
            field=models.CharField(blank=True, help_text='Ex: Fire Stick, Samsung Smart TV, Celular Android', max_length=200, verbose_name='Aparelho'),
        ),
    ]
