# Generated by Django 4.2.16 on 2026-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_add_aparelho_to_listacanais'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacanais',
            name='data_inicio_teste',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Teste'),
        ),
        migrations.AddField(
            model_name='listacanais',
            name='em_teste',
            field=models.BooleanField(default=False, verbose_name='Em Teste'),
        ),
    ]
