# Generated by Django 4.2.16 on 2026-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_add_em_teste_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacanais',
            name='controle_desde',
            field=models.DateField(blank=True, help_text='Preencha ao cadastrar clientes antigos. Mensalidades anteriores a esta data serão ignoradas no status e vencimento.', null=True, verbose_name='Controlar a partir de'),
        ),
    ]
