# Generated by Django 4.2.16 on 2026-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0006_add_controle_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiptv',
            name='instrucoes',
            field=models.TextField(blank=True, help_text='Modelo de texto para orientar o cliente no cadastro. Disponível para cópia rápida na listagem.', verbose_name='Instruções de Cadastro'),
        ),
    ]
