# Generated by Django 4.2.16 on 2026-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0010_move_dns_customizado_to_listaapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaapp',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento/renovação (ex: licença Clouddy)', null=True, verbose_name='Vencimento do App'),
        ),
    ]
