# Generated by Django 4.2.16 on 2026-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(blank=True, help_text='Como você chama essa pessoa. Usado nas mensagens do WhatsApp.', max_length=100, verbose_name='Apelido / Como chama'),
        ),
    ]
