# Generated by Django 4.2.16 on 2026-04-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_add_apelido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atrasado', 'Mensalidade Atrasada'), ('vencendo', 'Vencimento Próximo'), ('teste', 'Cliente em Teste')], max_length=20, unique=True, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
            },
        ),
    ]
